# Units of measurement
UnitVel = 1e5                   # 1 km/s
UnitMass = 1.989e43             # 10^10 Msol
UnitLength = 3.085678e21        # 1 kpc
UnitTime = 1e13                  # 1 Myr

# Grid parameters
Npoints = 100000                 # number of mass points
NgridX = 100                     # number of grid points
NgridY = 100                     # number of grid points
BoxSizeX = 1000                 # box size in x direction in kpc
BoxSizeY = 1000                 # box size in y direction in kpc

# Parameters for the density contrast
A_deltaPar = 0.01               # maximum density contrast
n_iter = 300                    # number of iterations